### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by Vortron-rd** [Felix3322/IXLAutoAnswer_OpenAI_API_Requid#4]
I noticed that this software is licensed under Creative Commons Attribution-NonCommercial 4.0 International.
I wanted to inform you that this license is not used for software and lacks information about how to handle it. From creative commons' [FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) : 

> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.
Our licenses are currently not compatible with the GPL, though the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry. We are looking into compatibility of BY-SA with GPL in the future; see the license compatibility page for more information.

I'd reccomend using something like the [MIT](https://choosealicense.com/licenses/mit/) license if you want to keep it open-source. You could also look for other licenses [here](https://choosealicense.com/).

Feel free to comment if you have any other questions.

**Comment by Felix3322** [comment]
I noticed this before, but I forgot to modify the license
